// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace GPSSampleDecoder.MacUI
{
	public partial class WIndowDialogViewController : NSViewController
	{
		public WIndowDialogViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
